executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: model
    json_schema:
      enum:
        - tts_models/multilingual/multi-dataset/xtts_v2
        - tts_models/multilingual/multi-dataset/xtts_v1.1
        - tts_models/multilingual/multi-dataset/your_tts
        - tts_models/multilingual/multi-dataset/bark
        - tts_models/bg/cv/vits
        - tts_models/cs/cv/vits
        - tts_models/da/cv/vits
        - tts_models/et/cv/vits
        - tts_models/ga/cv/vits
        - tts_models/en/ek1/tacotron2
        - tts_models/en/ljspeech/tacotron2-DDC
        - tts_models/en/ljspeech/tacotron2-DDC_ph
        - tts_models/en/ljspeech/glow-tts
        - tts_models/en/ljspeech/speedy-speech
        - tts_models/en/ljspeech/tacotron2-DCA
        - tts_models/en/ljspeech/vits
        - tts_models/en/ljspeech/vits--neon
        - tts_models/en/ljspeech/fast_pitch
        - tts_models/en/ljspeech/overflow
        - tts_models/en/ljspeech/neural_hmm
        - tts_models/en/vctk/vits
        - tts_models/en/vctk/fast_pitch
        - tts_models/en/sam/tacotron-DDC
        - tts_models/en/blizzard2013/capacitron-t2-c50
        - tts_models/en/blizzard2013/capacitron-t2-c150_v2
        - tts_models/en/multi-dataset/tortoise-v2
        - tts_models/en/jenny/jenny
        - tts_models/es/mai/tacotron2-DDC
        - tts_models/es/css10/vits
        - tts_models/fr/mai/tacotron2-DDC
        - tts_models/fr/css10/vits
        - tts_models/uk/mai/glow-tts
        - tts_models/uk/mai/vits
        - tts_models/zh-CN/baker/tacotron2-DDC-GST
        - tts_models/nl/mai/tacotron2-DDC
        - tts_models/nl/css10/vits
        - tts_models/de/thorsten/tacotron2-DCA
        - tts_models/de/thorsten/vits
        - tts_models/de/thorsten/tacotron2-DDC
        - tts_models/de/css10/vits-neon
        - tts_models/ja/kokoro/tacotron2-DDC
        - tts_models/tr/common-voice/glow-tts
        - tts_models/it/mai_female/glow-tts
        - tts_models/it/mai_female/vits
        - tts_models/it/mai_male/glow-tts
        - tts_models/it/mai_male/vits
        - tts_models/ewe/openbible/vits
        - tts_models/hau/openbible/vits
        - tts_models/lin/openbible/vits
        - tts_models/tw_akuapem/openbible/vits
        - tts_models/tw_asante/openbible/vits
        - tts_models/yor/openbible/vits
        - tts_models/hu/css10/vits
        - tts_models/el/cv/vits
        - tts_models/fi/css10/vits
        - tts_models/hr/cv/vits
        - tts_models/lt/cv/vits
        - tts_models/lv/cv/vits
        - tts_models/mt/cv/vits
        - tts_models/pl/mai_female/vits
        - tts_models/pt/cv/vits
        - tts_models/ro/cv/vits
        - tts_models/sk/cv/vits
        - tts_models/sl/cv/vits
        - tts_models/sv/cv/vits
        - tts_models/ca/custom/vits
        - tts_models/fa/custom/glow-tts
        - tts_models/bn/custom/vits-male
        - tts_models/bn/custom/vits-female
        - tts_models/be/common-voice/glow-tts
      ui:options:
        labels:
          - xtts_v2
          - xtts_v1.1
          - your_tts
          - bark
          - bg/cv/vits
          - cs/cv/vits
          - da/cv/vits
          - et/cv/vits
          - ga/cv/vits
          - en/ek1/tacotron2
          - en/ljspeech/tacotron2-DDC
          - en/ljspeech/tacotron2-DDC_ph
          - en/ljspeech/glow-tts
          - en/ljspeech/speedy-speech
          - en/ljspeech/tacotron2-DCA
          - en/ljspeech/vits
          - en/ljspeech/vits--neon
          - en/ljspeech/fast_pitch
          - en/ljspeech/overflow
          - en/ljspeech/neural_hmm
          - en/vctk/vits
          - en/vctk/fast_pitch
          - en/sam/tacotron-DDC
          - en/blizzard2013/capacitron-t2-c50
          - en/blizzard2013/capacitron-t2-c150_v2
          - en/multi-dataset/tortoise-v2
          - en/jenny/jenny
          - es/mai/tacotron2-DDC
          - es/css10/vits
          - fr/mai/tacotron2-DDC
          - fr/css10/vits
          - uk/mai/glow-tts
          - uk/mai/vits
          - zh-CN/baker/tacotron2-DDC-GST
          - nl/mai/tacotron2-DDC
          - nl/css10/vits
          - de/thorsten/tacotron2-DCA
          - de/thorsten/vits
          - de/thorsten/tacotron2-DDC
          - de/css10/vits-neon
          - ja/kokoro/tacotron2-DDC
          - tr/common-voice/glow-tts
          - it/mai_female/glow-tts
          - it/mai_female/vits
          - it/mai_male/glow-tts
          - it/mai_male/vits
          - ewe/openbible/vits
          - hau/openbible/vits
          - lin/openbible/vits
          - tw_akuapem/openbible/vits
          - tw_asante/openbible/vits
          - yor/openbible/vits
          - hu/css10/vits
          - el/cv/vits
          - fi/css10/vits
          - hr/cv/vits
          - lt/cv/vits
          - lv/cv/vits
          - mt/cv/vits
          - pl/mai_female/vits
          - pt/cv/vits
          - ro/cv/vits
          - sk/cv/vits
          - sl/cv/vits
          - sv/cv/vits
          - ca/custom/vits
          - fa/custom/glow-tts
          - bn/custom/vits-male
          - bn/custom/vits-female
          - be/common-voice/glow-tts
    value: tts_models/multilingual/multi-dataset/xtts_v2
  - handle: model_path
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - handle: device
    json_schema:
      enum:
        - cpu
        - cuda
      ui:options:
        labels:
          - CPU
          - CUDA
    value: cpu
outputs_def:
  - handle: model
    json_schema:
      contentMediaType: oomol/var
    kind: tts_model
title: Load TTS model
ui:
  default_width: 443.1714091352669
