executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: input
    json_schema:
      type: string
outputs_def:
  - handle: output
    json_schema:
      type: string
title: Load conversion model
