executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: model
    json_schema:
      contentMediaType: oomol/var
    kind: conversion_model
  - handle: source_speaker
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        excludeAll: true
        filters:
          - name: WAV
            extensions:
              - wav
              - wave
  - handle: target_speaker
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        excludeAll: true
        filters:
          - name: WAV
            extensions:
              - wav
              - wave
  - handle: output_path
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: WAV
            extensions:
              - wav
              - wave
    value:
    nullable: true
outputs_def:
  - handle: output_path
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: WAV
            extensions:
              - wav
              - wave
    kind: conversion_model
title: Conversion
ui:
  default_width: 444.1232510653409
