executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: input
    json_schema:
      type: string
  - handle: model
    json_schema:
      contentMediaType: oomol/var
    kind: model
outputs_def:
  - handle: output
    json_schema:
      type: string
title: Conversion
